name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      # Build and push frontend image
      - name: Build Frontend Docker Image
        run: docker build -t ghcr.io/${REPO}/frontend:latest ./frontend
      - name: Push Frontend Docker Image
        run: docker push ghcr.io/${{ github.repository }}/frontend:latest

      # Build and push API image
      - name: Build API Docker Image
        run: docker build -t ghcr.io/${REPO}/api:latest ./api
      - name: Push API Docker Image
        run: docker push ghcr.io/${REPO}/api:latest

      # Stop docker compose
      - name: Stop docker compose
        run: |
          docker compose down


      # Pull docker images
      - name: Pull docker images
        run: |
          docker compose pull --ignore-pull-failures
        
      # Start docker compose
      - name: Start docker compose
        run: |
          docker compose up -d
